DISCORD_BOT_TOKEN = 'YOUR_DISCORD_BOT_TOKEN'

GROQ_API_KEY = 'YOUR_GROQ_API_KEY'
MANTIS_API_TOKEN = 'YOUR_MANTIS_API_TOKEN'
MANTIS_PROJECT_ID = YOUR_PROJECT_ID  # Integer
MANTIS_CATEGORY = 'General'
MANTIS_BASE_URL = 'https://your-subdomain.mantishub.io'

DB_FILE = 'tickets.db'
